### PR TITLE
change VNM format rule from 6Digits to 5Digits

### PR DESCRIPTION
**Pull request by tamonmon0417**
Postal code rule of VNM has changed.
Now they use 5Digits format for postal code!
Please review it.

Ref. https://en.wikipedia.org/wiki/Postal_codes_in_Vietnam

### CODE REVIEW

**Comment by tamonmon0417** [comment]
Could anyone review this PR please?

**Comment by ozankaya** [comment]
Can you please bump the minor version in the package.json and package-lock.json files so that this change publishes to npm automatically?

**Comment by tamonmon0417** [comment]
Okay I'll change it from 2.2.5 to 2.3.0.

**Comment by tamonmon0417** [comment]
I updated version in the package.json and package-lock.json

**Comment by tamonmon0417** [comment]
May I know why current build is failed?
https://github.com/Cimpress-MCP/postal-codes-js

**Comment by ozankaya** [comment]
> @ozankaya May I know why current build is failed?
> https://github.com/Cimpress-MCP/postal-codes-js

https://github.com/Cimpress-MCP/postal-codes-js/pull/47

**Pull request merged**
